server:
  port: 8082
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:chat_dev
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100 # Lazy ??? ? ? ??? DB?? ???? ???? ?
        show_sql: true # SQL ??? ?? ?? ???
        format_sql: true # SQL ??? ?????
        use_sql_comments: true # SQL ??? ???
  logging:
    level:
      # SQL? ??? ?? ????, SQL? ??? ??
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.orm.jdbc.extract: TRACE
      org.springframework.transaction.interceptor: TRACE